### ISSUE TITLE
Unpack Action Fails if the Canvas App does not contain any Component

### ISSUE THREAD

**Issue by LinnZawWin** [daryllabar/CanvasAppPackager#23]
Unpack Action Fails if the Canvas App does not contain any Component
Once a new component is created in the app and retry the unpack, the following error no longer occurs.

`Extracting files from C:\Temp\CanvasApps\ChallengesApp(Developer1)_20200210091630.zip to C:\Temp\CanvasApps\ChallengesAppDeveloper1
Extracting App Challenges App - Attendees at Microsoft Ignite 2018 Power Platform in a Day event will use this app to complete a number of challenges using PowerApps, Flow, Common Data Service, SharePoint & Power BI.
Extracting files from C:\Temp\CanvasApps\ChallengesAppDeveloper1\Microsoft.PowerApps\apps\1007466488935865233\N73e6a828-2800-4170-945d-546f5b1e7be8-document.msapp to C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App
Extracting file C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Controls\1.json
Extracting file C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Controls\28.json
Extracting file C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Controls\3.json
Extracting file C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Resources\PublishInfo.json
Renaming auto named file 'C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Resources\nsvk01e5.jpg' to 'C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Resources\Logo.jpg'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\CanvasApps\ChallengesAppDeveloper1\Apps\Challenges App\Components'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path)
   at CanvasAppPackager.UnpackLogic.RenameAutoNamedFiles(String appDirectory) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 120
   at CanvasAppPackager.UnpackLogic.Unpack(String file, String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 59
   at CanvasAppPackager.UnpackLogic.ExtractApps(String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 77
   at CanvasAppPackager.UnpackLogic.Unpack(String file, String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 59
   at CanvasAppPackager.Program.Unpack(Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\Program.cs:line 79
   at CanvasAppPackager.Program.Main(String[] args) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\Program.cs:line 39
Finished!`

**Comment by daryllabar** [comment]
Hey @LinnZawWin does this work?

[CanvasAppPackager.zip](https://github.com/daryllabar/CanvasAppPackager/files/4181701/CanvasAppPackager.zip)

If not, could you give me your export file so i can get it to extract smoothly?

**Comment by LinnZawWin** [comment]
@daryllabar That version in the comment above is working fine with no error for that "Components folder not found" issue.
