### ISSUE TITLE
System.Exception: Unable to re-serialize json

### ISSUE THREAD

**Issue by MarcoOswald** [daryllabar/CanvasAppPackager#37]
Hi, I got the following error on multiple canvas apps, which I tried to unpack.

System.Exception: Unable to re-serialize json to match source!  Character at position: 1843 on line: 0 at 1844 is not correct.  To prevent potential app defects, extracting file C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json has stopped.
See 'C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json.original' for extracted version vs output version 'C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json.reserialized'.Character at position: 23392 on line: 1 at 0 is not correct.  To prevent potential app defects, extracting file C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json has stopped.
See 'C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json.original.json' for extracted formatted version vs output formatted version 'C:\Program Files\DynamicsUtility\Tools\SPPoc\ext\Apps\FormToJson\Controls\103.json.reserialized.json'.
   at CanvasAppPackager.UnpackLogic.VerifySerialization(CanvasAppScreen screen, String json, String file, Version docVersion) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 244
   at CanvasAppPackager.UnpackLogic.ExtraCodeful(String controlsDir, String codeDirectory, Version version, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 202
   at CanvasAppPackager.UnpackLogic.ExtractCanvasApp(String appDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 180
   at CanvasAppPackager.UnpackLogic.Unpack(String file, String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 62
   at CanvasAppPackager.UnpackLogic.ExtractApps(String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 80
   at CanvasAppPackager.UnpackLogic.Unpack(String file, String outputDirectory, Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\UnpackLogic.cs:line 62
   at CanvasAppPackager.Program.Unpack(Args options) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\Program.cs:line 89
   at CanvasAppPackager.Program.Main(String[] args) in C:\Users\DarylLaBar\source\repos\CanvasAppPackager\CanvasAppPackager\Program.cs:line 49

Here the demo app
[FormToJson_20210413091552.zip](https://github.com/daryllabar/CanvasAppPackager/files/6302596/FormToJson_20210413091552.zip)

Best regards,

Marco

**Comment by daryllabar** [comment]
Sorry Marco, since Microsoft now has their own version of the tool that they will be supporting, I'm not planning on updating the project any more.  You can check it out here: https://github.com/microsoft/PowerApps-Language-Tooling
